#!/bin/bash
#PBS -N testMirlibHadoop
#PBS -l nodes=2:ppn=8
#PBS -l walltime=00:04:00
#PBS -A hvg-164-aa
#PBS -o jobsOut/$MOAB_JOBID.out
#PBS -e jobsOut/$MOAB_JOBID.err
#PBS -E

cd "${PBS_O_WORKDIR}"

module load apps/spark/2.0.0

module load compilers/gcc/4.8.5
module load compilers/java/1.8
# This line is required only if we use cutadapt (this pipeline works with 2.7, tested)
module load apps/python/2.7.5
#
module load apps/bowtie/1.1.0
module load apps/mugqic_pipeline/2.1.1
module load mugqic/blast/2.2.31+
module load mugqic/ViennaRNA/2.1.8

# Launch Spark cluster
start-all.sh
 
# Submit SparkPi.jar application to the Spark cluster
spark-submit --master spark://$HOSTNAME:7077 ../src/mirLibPipeline.py ../paramfile.txt
# Stop Spark cluster
stop-all.sh
