#!/bin/bash
#PBS -N allmirbase_model
#PBS -l nodes=2:ppn=8
#PBS -l walltime=03:00:00
#PBS -A hvg-164-aa
#PBS -o jobsOut/$MOAB_JOBID.out
#PBS -e jobsOut/$MOAB_JOBID.err
#PBS -E

cd "${PBS_O_WORKDIR}"

module load compilers/gcc/4.8.5
module load compilers/java/1.8
module load apps/mugqic_pipeline/2.1.1
module load mugqic/ViennaRNA/2.1.8

 
# Submit creating all miRBase model
java -jar ../lib/miRdup_1.4/miRdup.jar -r /software6/bioinfo/apps/mugqic_space/software/ViennaRNA/ViennaRNA-2.1.8/bin/

